# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get install qt6-default libssl-dev
  displayName: "Install Required Dependency"
- task: CMake@1
  displayName: 'Init CMake Files for build'
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '..'
- task: CMake@1
  displayName: "Build the src"
  inputs:
    workingDirectory: "build"
    cmakeArgs: "--build ."

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
